### ISSUE TITLE
Seperate messages into categories

### ISSUE THREAD

**Issue by NeunEinser** [mojira/helper-messages#97] opened 2020-07-28 12:46 UTC
Currently, it is often hard to find the correct message, with the increasing amount of messages and the dropdown becoming longer and longer as messages get added.
A possible solution to this could be to separate them into categories, by which they are sorted and maybe have some bold text as a separator in the dropdown (similarily to Jira: 
![image](https://user-images.githubusercontent.com/12124394/88666016-c800c700-d0df-11ea-9d0a-27d8514d35cf.png)

This is also a possible alternate solution to #96, as certain applications could filter certain categories (and thus make Bot messages not appear on the site at all).

Possible categories could include:
- Duplicate
- Invalid
- Awaiting Response
- Panels / Notices
- Misc
- Bot messages

**Comment by MikeUnverferth** [comment] 2020-07-28 19:12
Would want to include Incomplete also. What would be even more useful (to me anyway) would be to have the most commonly used messages available with a single click. Those would be Duplicate, Incomplete, A-R, and various Invalid ones. Others would probably want different ones though.

Or could they just all be listed on a page, organized by categories, and eliminate the selection dropdown entirely?

Duplicate of [     ]
  General  Fixed  Private  WAI  Wont Fix

Invalid
  General  Crash  Feature  Multiple  Parity  Wrong Project  External Server  Modified Game
  Mojang Support  Community Support  Not English  Parity  Service Outage

Awaiting Response
  General  Attach New Attachment  Attach Screenshot  Attach Video  (do we really need all these?)

Miscellaneous
  Incomplete  WAI  Quick-Links

Panels / Notices
  ...

**Comment by NeunEinser** [comment] 2020-07-29 23:54
> Would want to include Incomplete also.

That would be one for misc. There is only one message for that, so no need for an extra category.

> General Attach New Attachment Attach Screenshot Attach Video (do we really need all these?)

Those a very useful yes, at least in my opinion. Except "Attach new attachment" which is mostly used by Arisa when an attachment was automatically deleted (but could also be used by a mod in case of a manual action)

> Or could they just all be listed on a page, organized by categories, and eliminate the selection dropdown entirely?

It could make sense to have a dropdown per category or something else. We could make a mockup for a new design.

**Closed** 2022-07-19 19:16 UTC
Labels: enhancement
